# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5165911823acd296ce409c766895c900779ff76e2935aa1b53bcd1e8b9178dec357d9313f546c5c3258eb8157fa20d5541a7dcfbc7bc793a8cf492e0c7991a1

test:
  secret_key_base: fcdd7cad3c45b1d26f414cf48e3e1fa8c667beafef78f6f6cb784f7938eb6e02fb1d65b1c2984d52214b21aa2f59de14a93eff45f9ea70d5c66f2fa08bed209d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
